#!/usr/bin/env bash

[ -d build ] && rm -rf build

# cmake -S . -B build -G Ninja
# cmake --build build
# cmake --install build --prefix build/install

# FLASH_ARGS="--serial 0670FF373146363143202623" ninja -C build upload_CANMonitor

# nix build .#default

# cd ../..
# bin/run